name: Deploy Lambda Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::971674965395:role/datadev-dev
          aws-region: us-east-1

      - name: Install AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest

      - name: Create zip for Lambda function
        run: |
          zip -r code.zip . -x ".git/*" ".github/*"

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:971674965395:function:githubaction \
            --zip-file fileb://code.zip

      - name: Sanity check
        run: aws sts get-caller-identity
