name: Deploy Lambda Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::971674965395:role/github.to.aws.oicd
          aws-region: us-east-1

      - name: Sanity check (who am I?)
        run: aws sts get-caller-identity

      - name: Create zip for Lambda function
        run: |
          # exclude VCS/workflow dirs and the zip itself if it exists
          zip -r code.zip . -x ".git/*" ".github/*" "code.zip"

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:971674965395:function:githubaction \
            --zip-file fileb://code.zip
          # If you want to create a new published version each deploy, add: --publish
